#!/bin/bash

# Function to remove the oldest backup if there are more than 7 backups
cleanup_old_backups() {
  BACKUPS=($(ls -dt ${OUTPUT_DIR}/${DB_NAME}_*))
  NUM_BACKUPS=${#BACKUPS[@]}
  
  if [ "$NUM_BACKUPS" -gt 7 ]; then
    OLDEST_BACKUP=${BACKUPS[-1]}
    echo "$TIMESTAMP - Removing oldest backup: ${OLDEST_BACKUP}" >> $LOG_FILE
    rm -rf "${OLDEST_BACKUP}"
  fi
}



# --------------------------------------------------------------------
# MAIN Script
# --------------------------------------------------------------------

# Check if the correct number of arguments are provided
if [ "$#" -ne 2 ]; then
  echo
  echo "Usage: $0 <database_name> <backup_directory>"
  echo
  exit 1
fi

# Check if mongod service is running
if ! pgrep mongod > /dev/null; then
  echo
  echo "MongoDB service is not running. Please start the mongod service."
  echo
  exit 1
fi

# Variables
DB_NAME="$1"
OUTPUT_DIR="$2"
LOG_FILE="/data/mongo_data_backup/log"
TIMESTAMP=$(date +"%F_%T")
OUTPUT_PATH="${OUTPUT_DIR}/${DB_NAME}_${TIMESTAMP}"

# Create the output directory if it does not exist
mkdir -p "${OUTPUT_DIR}"

# Run mongodump and capture output and error
DUMP_OUTPUT=$(mongodump --db "${DB_NAME}" --out "${OUTPUT_PATH}" 2>&1)
DUMP_EXIT_STATUS=$?

# Check if mongodump was successful
if [ ${DUMP_EXIT_STATUS} -eq 0 ]; then
  echo "$TIMESTAMP - Backup successful: ${OUTPUT_PATH}" >> $LOG_FILE
  # Remove oldest backup
  cleanup_old_backups
else
  echo "$TIMESTAMP - Backup failed" >> $LOG_FILE
  exit 1
fi
